version: "3.8"

services:

  spring-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_container
    restart: always
    ports:
      - "8889:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://112.137.129.158:5001/campuslearning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dungcon2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-net
    volumes:
      - /home/nguyenducduong/campuslearning/uploads:/app/uploads

networks:
  app-net:
    external: true