version: "3.8"

services:

  spring-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_container
    restart: always
    ports:
      - "8889:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/campuslearning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dungcon2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql_container:
        condition: service_healthy
    networks:
      - app-net
    volumes:
      - ./uploads:/app/uploads

networks:
  app-net:
    external: true
