version: "3.8"

services:
  # ðŸ”¹ MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dungcon2005
      MYSQL_DATABASE: campuslearning
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-admin:
    build:
      context: ./BackEnd-CampusLearningAdmin
      dockerfile: Dockerfile
    container_name: spring_container
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/campuslearning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dungcon2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-net
    volumes:
      - ./uploads:/app/uploads

networks:
  app-net:
